# Generated by Django 3.1.4 on 2021-05-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('naissance', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('format', models.IntegerField(help_text='Hauteur')),
                ('pages', models.IntegerField()),
                ('tags', models.TextField(blank=True)),
                ('livrelu', models.CharField(blank=True, max_length=255)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tablodebord.auteur')),
            ],
        ),
    ]
