# Generated by Django 3.1.7 on 2021-11-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablodebord', '0002_auto_20210504_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='resume',
            field=models.TextField(blank=True),
        ),
    ]
